In [5]:
from scipy import stats
import numpy as np
import pandas as pd

In [7]:
glaxo_df = pd.read_csv('/content/Data-Science/Statistics/glaxo_df.csv')
glaxo_df.head()

         Date      Date.1    Close      gain
0  2010-01-05  2010-01-05  1616.80 -0.005444
1  2010-01-06  2010-01-06  1638.50  0.013422
2  2010-01-07  2010-01-07  1648.70  0.006225
3  2010-01-08  2010-01-08  1639.80 -0.005398
4  2010-01-11  2010-01-11  1629.45 -0.006312

In [9]:
glaxo_df_ci = stats.norm.interval(0.95,loc=glaxo_df.gain.mean(),scale=glaxo_df.gain.std())
print("Gain at 95% confidence interval is: ", np.round(glaxo_df_ci,4))

Gain at 95% confidence interval is:  [-0.0258  0.0266]

In [10]:
beml_df = pd.read_csv('/content/Data-Science/Statistics/beml_df.csv')
beml_df.head()

         Date      Date.1    Close      gain
0  2010-01-05  2010-01-05  1134.60 -0.000881
1  2010-01-06  2010-01-06  1139.60  0.004407
2  2010-01-07  2010-01-07  1144.15  0.003993
3  2010-01-08  2010-01-08  1144.05 -0.000087
4  2010-01-11  2010-01-11  1137.00 -0.006162

In [12]:
beml_df_ci = stats.norm.interval(0.95,loc=beml_df.gain.mean(),scale=beml_df.gain.std())
print("Gain at 95% confidence interval is: ", np.round(beml_df_ci,4))

Gain at 95% confidence interval is:  [-0.0515  0.0521]

In [ ]:
cp "/content/drive/MyDrive/Colab Notebooks/Visualization.ipynb" "/content/Data-Science/Python/"